add instance piped.moomoo.me
libredirect/libredirect pull request #168
Opened 2022-04-02 17:17 UTC by lucamp

this instance is working really well in Italy

also removed last / from line 98:
"https://piped.notyourcomputer.net/"

2022-04-03 02:30 UTC, EdwardLangdon commented
"https://piped.notyourcomputer.net/" it is working well. And I can access it. You haven't removed the Instance yet from the code. So, Don't do it.

The Reason, we haven't added moomoo Instance frontend URL. It is only available to use via API most of the time. So, At the time of adding Instances moomoo.me wasn't working. So, We haven't added. Now, The frontend seems to be online. In my POV, The Frontend of Moomoo is known for many Downtimes.

We shall see whether we will merge this PR or not after speaking with @ManeraKai

2022-04-03 05:29 UTC, lucamp commented
@EdwardLangdon I didn't state that I will remove notyourcomputer.net. Please read again my first message.

Notmycomputer is localed in US and has no CDN, from Italy it's slower than moomoo.me (or silkky.cloud)

I have no idea when you checked moomoo.me, from my Italy no issue in 2 weeks and one of the best ping

2022-04-03 05:50 UTC, EdwardLangdon commented
You can see my PR here - https://github.com/libredirect/libredirect/pull/132. I checked it about 11 days ago. At the time, I cannot access it. I am from Swiss.

>Please read again my first message.
Sorry, I didn't understand what you meant at the time. I get it now.

2022-04-03 05:54 UTC, EdwardLangdon commented
As of now, I cannot access piped.notyourcomputer.net. Are you able to access it ?

For moomoo.me, I am talking about availability all the time. Let's wait for a few days. If you can, Log that, from now, Day 1 to Day 10 from Now on. How often you can access Moomoo Instance.

We want to be sure that the addition must be worth the thing. Not the one unavailable after running it.

2022-04-03 05:59 UTC, lucamp commented
> As of now, I cannot access piped.notyourcomputer.net. Are you able to access it ?

Up and running. Maybe a DNS issue? 

> For moomoo.me, I am talking about availability all the time. Let's wait for a few days. If you can, Log that, from now, Day 1 to Day 10 from Now on. How often you can access Moomoo Instance.

No problem

2022-04-03 06:01 UTC, EdwardLangdon commented
> Up and running. Maybe a DNS issue?

You are right.

2022-04-08 02:34 UTC, ManeraKai commented
5 days have passed. I'll merge it.

2022-04-08 02:35 UTC, ManeraKai commented
For me it it gives a 502 Error from Cloudflare even through Tor.

2022-04-08 06:21 UTC, lucamp commented
> For me it it gives a 502 Error from Cloudflare even through Tor.

Piped.moomoo.me is down since few hours ago, [https://status.moomoo.me](https://status.moomoo.me)

There have been other downs that as a end user I did not noticed and at this point is not reliable

2022-04-08 11:38 UTC, EdwardLangdon commented
@lucamp Are you making logs as I requested ?

2022-04-08 15:45 UTC, lucamp commented
> @lucamp Are you making logs as I requested ?

As I wrote in my previous message, piped.moomoo.me was down. And at [https://status.moomoo.me/](https://status.moomoo.me/) you can check the previous incident, such as the one you reported.

There is no point to keep logging something that breaks every 2 weeks, and to include it in the list as a default instance. Just reject this pull

2022-04-09 06:36 UTC, EdwardLangdon requested changes
All Good. Just rearrange the list according to the official list after this PR is merged - https://github.com/libredirect/libredirect/pull/179

2022-04-09 06:38 UTC, EdwardLangdon commented
@lucamp according to the Status page it is down only at certain Intervals and seems to be up. I think we can add this Instance, If it is ever offline, It will autmatically redirect to another one which is online.

2022-04-09 11:21 UTC, EdwardLangdon requested changes

2022-04-09 11:21 UTC, EdwardLangdon commented on src/assets/javascripts/helpers/youtube/youtube.js
> +      "https://piped.notyourcomputer.net"
Add `,` at the end of line 98.

2022-04-09 11:24 UTC, merged